name: test

on:
  push:
    branches: [sample]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift run swiftpmTest ${{ secrets.GITHUB_TOKEN }}